public class class01 {

    public static void main (String[] args){

        //V1 calismalarimmm....
        //V2 calismalarimmm....
     System.out.println("v3 kodlarim");
        //V2 calismalarimmm....
        //V3 yenisi calismalarimmm....
        // github degisikleri.
        
    }
}
